services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    depends_on:
      - db
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "3001:3001"
    volumes:
      - ./app:/app
    depends_on:
      - api
  db:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
